-- MySQL Script generated by MySQL Workbench
-- Tue Oct  9 13:25:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wechat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wechat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wechat` DEFAULT CHARACTER SET utf8 ;
USE `wechat` ;

-- -----------------------------------------------------
-- Table `wechat`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wechat`.`account` ;

CREATE TABLE IF NOT EXISTS `wechat`.`account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '公众号名称',
  `appid` VARCHAR(45) NOT NULL DEFAULT '',
  `tocken` VARCHAR(45) NOT NULL DEFAULT '',
  `created_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `account_type` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '类型\n1 未认证订阅号\n2 微信认证订阅号\n3 未认证服务号\n4 微信认证服务号',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = '公众号';


-- -----------------------------------------------------
-- Table `wechat`.`fan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wechat`.`fan` ;

CREATE TABLE IF NOT EXISTS `wechat`.`fan` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `wx` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '微信号id',
  `nickname` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '昵称',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '关注时间',
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '解除关注时间',
  `account_id` INT UNSIGNED NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '粉丝完整信息状态\n1 完整\n2 不完整',
  PRIMARY KEY (`id`),
  INDEX `fk_fans_account1_idx` (`account_id` ASC) )
ENGINE = MyISAM
COMMENT = '粉丝';


-- -----------------------------------------------------
-- Table `wechat`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wechat`.`event` ;

CREATE TABLE IF NOT EXISTS `wechat`.`event` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `send_content` VARCHAR(255) NULL DEFAULT '' COMMENT '发送内容',
  `reply_content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '回复内容',
  `event_type` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '消息类型\n1关注/取消关注事件\n2扫描带参数二维码事件\n3上报地理位置事件\n4自定义菜单事件\n5点击菜单拉取消息时的事件推送\n6点击菜单时跳转链接时的事件推送\n',
  `send_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '发送时间',
  `account_id` INT UNSIGNED NOT NULL COMMENT '公众号ID',
  `fan_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_account1_idx` (`account_id` ASC) ,
  INDEX `fk_message_fans1_idx` (`fan_id` ASC) )
ENGINE = MyISAM
COMMENT = '事件';


-- -----------------------------------------------------
-- Table `wechat`.`material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wechat`.`material` ;

CREATE TABLE IF NOT EXISTS `wechat`.`material` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pid` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父级',
  `title` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '标题',
  `pic` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '图片',
  `author` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '作者',
  `digest` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '描述',
  `content` TEXT NOT NULL COMMENT '内容',
  `url` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '访问链接',
  `content_source_url` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '原文链接',
  `thumb_media_id` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '图片资源',
  `media_id` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '文件资源',
  `show_cover_pic` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否显示封面',
  `material_type` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1 临时\n2 永久\n3 群发',
  `account_id` INT UNSIGNED NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '素材状态\n1 正常\n2 添加\n3 删除',
  `source_type` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '资源类型\nimage\nvoice\nvideo\nthumb\nNews',
  `created_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本地素材创建时间',
  `updated_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本地素材修改时间',
  `wx_created_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '微信服务器素材创建时间',
  `wx_updated_at` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '微信服务器素材修改时间',
  PRIMARY KEY (`id`),
  INDEX `fk_material_account1_idx` (`account_id` ASC) )
ENGINE = MyISAM
COMMENT = '素材\n';


-- -----------------------------------------------------
-- Table `wechat`.`acount_statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wechat`.`acount_statistics` ;

CREATE TABLE IF NOT EXISTS `wechat`.`acount_statistics` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text_num` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文本消息发送次数',
  `media_num` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '图文发送次数',
  `preview_num` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '预览消息发送次数',
  `group_num` INT UNSIGNED NOT NULL COMMENT '群发消息发送次数',
  `fans_ids` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '粉丝ids',
  `send_time` DATE NOT NULL COMMENT '按月统计',
  `account_id` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `fk_statistics_account1_idx` (`account_id` ASC) )
ENGINE = MyISAM
COMMENT = '群发消息统计';


-- -----------------------------------------------------
-- Table `wechat`.`message_statistics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wechat`.`message_statistics` ;

CREATE TABLE IF NOT EXISTS `wechat`.`message_statistics` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message_num` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '文本消息发送次数',
  `forver_num` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '永久消息发送次数',
  `temporary_num` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '临时消息发送次数',
  `account_id` INT UNSIGNED NOT NULL,
  `fan_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_statistics_account1_idx` (`account_id` ASC) ,
  INDEX `fk_fans_statistics_fans1_idx` (`fan_id` ASC) )
ENGINE = MyISAM
COMMENT = '被动回复消息统计';


-- -----------------------------------------------------
-- Table `wechat`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wechat`.`menu` ;

CREATE TABLE IF NOT EXISTS `wechat`.`menu` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '菜单名称',
  `type` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '菜单类型',
  `content` VARCHAR(45) NOT NULL DEFAULT '' COMMENT 'Url \\ key\\ media_id',
  `pid` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `account_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_menu_account1_idx` (`account_id` ASC) )
ENGINE = MyISAM
COMMENT = '菜单';


-- -----------------------------------------------------
-- Table `wechat`.`message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wechat`.`message` ;

CREATE TABLE IF NOT EXISTS `wechat`.`message` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `message_type` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '被动回复\n1 文本消息\n2 图片消息\n3 语音消息\n4 视频消息\n5 音乐消息\n6 图文消息',
  `send_content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '发送内容',
  `reply_content` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '回复内容',
  `send_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '发送时间',
  `fan_id` INT UNSIGNED NOT NULL,
  `account_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_fans2_idx` (`fan_id` ASC) ,
  INDEX `fk_message_account2_idx` (`account_id` ASC) )
ENGINE = MyISAM
COMMENT = '被动消息';


-- -----------------------------------------------------
-- Table `wechat`.`group_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wechat`.`group_history` ;

CREATE TABLE IF NOT EXISTS `wechat`.`group_history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '发送内容',
  `send_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '发送时间',
  `account_id` INT UNSIGNED NOT NULL,
  `material_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_history_account1_idx` (`account_id` ASC) ,
  INDEX `fk_group_history_material1_idx` (`material_id` ASC) )
ENGINE = MyISAM
COMMENT = '群发消息';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
