-- MySQL Script generated by MySQL Workbench
-- Thu Oct 11 23:26:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wegou
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wegou
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wegou` DEFAULT CHARACTER SET utf8 ;
USE `wegou` ;

-- -----------------------------------------------------
-- Table `wegou`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wegou`.`account` ;

CREATE TABLE IF NOT EXISTS `wegou`.`account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL DEFAULT '' COMMENT '公众号名称',
  `appid` VARCHAR(255) NOT NULL DEFAULT '',
  `appsecret` VARCHAR(255) NOT NULL DEFAULT '',
  `aeskey` VARCHAR(255) NOT NULL DEFAULT '',
  `oriid` VARCHAR(255) NOT NULL DEFAULT '',
  `tocken` VARCHAR(255) NOT NULL DEFAULT '',
  `created_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_time` INT UNSIGNED NOT NULL DEFAULT 0,
  `account_type` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '类型\n1 未认证订阅号\n2 微信认证订阅号\n3 未认证服务号\n4 微信认证服务号\n5 测试公众号',
  `service_type` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '服务类型\n1 免费服务\n2 收费服务',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '服务状态\n1正常\n2停止',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
COMMENT = '公众号';





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
